services:
  # Rabbit
  rabbit:
    image: "rabbitmq:3.12-management"
    container_name: "rabbit"
    ports:
      - "${RABBIT_PORT}:5672"
      - "1${RABBIT_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBIT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBIT_PASS}"
    volumes:
      - rabbit_volume:/var/lib/rabbitmq
    restart: always
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s