spring:
  application:
    name: fbot
  output:
    ansi:
      enabled: always
  profiles:
    default: "dev"

server:
  port: ${APP_PORT}

logging:
  level:
    org:
      springframework:
        amqp: DEBUG
    root: DEBUG

telegram:
  bot:
    token: ${BOT_TOKEN}

kafka:
  bootstrap-servers: ${KAFKA_SERVER}